name: Python application

on:
  push:
    branches: [ "DEV" ]
  pull_request:
    branches: [ "DEV" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with coverage
      run: |
        coverage run rpa.py
        coverage report

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Build Docker image
      run: docker build -t marcusvrt0/projeto_rpa:${{ github.run_number }} .

    - name: Push Docker image
      run: docker push marcusvrt0/projeto_rpa:${{ github.run_number }}
